//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFinderProject.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentID { get; set; }
        public int UserID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Description { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
