//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFinderProject.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int FavoriteID { get; set; }
        public int UserID { get; set; }
        public int DoctorID { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Users Users { get; set; }
    }
}
