//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFinderProject.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecords
    {
        public int RecordID { get; set; }
        public int CardID { get; set; }
        public int DoctorID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Diagnosis { get; set; }
        public string Recommendations { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual MedicalCards MedicalCards { get; set; }
    }
}
