//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFinderProject.dbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalSpecialistServiceEntities4 : DbContext
    {
        public MedicalSpecialistServiceEntities4()
            : base("name=MedicalSpecialistServiceEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Clinics> Clinics { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<DoctorSchedules> DoctorSchedules { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<MedicalCards> MedicalCards { get; set; }
        public virtual DbSet<MedicalRecords> MedicalRecords { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
