//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFinderProject.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ServiceID { get; set; }
        public int DoctorID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
